# TODO make conditional on storageClass in values.yaml 
#---
#kind: PersistentVolume
#apiVersion: v1
#metadata:
#  name: shared
#  labels:
#    type: local
#spec:
#  capacity:
#    storage: 1Gi
#  accessModes:
#    - ReadWriteMany
#  hostPath:
#    path: "/tmp"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: composer-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-dynamic"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
